### PR TITLE
Retrieve commit data

### PR DESCRIPTION
**Pull request by BoredX**
There is also a per minute request limit to github, so we may have to clone a library use a library like nodegit. Too many requests per minute if requesting a lot of commits and their file content.

### CODE REVIEW

**Comment by mrbrendanwong** [comment]
Looks good. Thanks for the hard work

**Comment by wong-alan** [comment]
Looks good to me too 👍

**Comment by thethomasz** [comment]
dis suk

**Comment by mrbrendanwong** [comment]
mine better

**Pull request closed without merging**
